<?php

return array (
  'services' => 
  array (
    'time' => 'Time required',
    'percent' => 'percent',
    'fixed' => 'fixed',
    'discount' => 'Discount',
    'discountedPrice' => 'Price after discount',
  ),
  'settings' => 
  array (
    'openTime' => 'Open Time',
    'closeTime' => 'Close Time',
    'allowBooking' => 'Allow booking',
    'allowMultipleBooking' => 'Allow multiple bookings for same date and time?',
    'slotDuration' => 'Slot Duration',
  ),
  'booking' => 
  array (
    'selectCustomer' => 'Select Customer',
    'customerDetails' => 'Customer Details',
    'searchNote' => 'Search a customer by name, email or mobile',
    'payViaCash' => 'Pay by cash',
    'payViaCard' => 'Pay by card',
    'cashGivenByCustomer' => 'Cash given by customer',
    'cashToReturn' => 'Cash to return',
    'cashRemaining' => 'Cash remaining',
    'addItemsToCart' => 'Add item to cart.',
    'emptyCart' => 'Empty Cart',
    'paymentMethod' => 'Payment Method',
    'paymentStatus' => 'Payment Status',
    'billedTo' => 'Billed To',
    'generatedBy' => 'Generated By',
    'requestCancellation' => 'Cancel Booking',
    'earning' => 'Earning',
    'sendReminder' => 'Send Reminder',
    'customerMessage' => 'Customer Message',
    'changeStatus' => 'Change Status',
    'selectStatus' => 'Select Status',
    'selectNote' => 'Click booking to select it.',
    'selectLocation' => 'Select Location',
    'changePaymentStatus' => 'Change Payment Status to Completed?',
  ),
  'emailSettings' => 
  array (
    'mailDriver' => 'Mail Driver',
    'mailHost' => 'Mail Host',
    'mailPort' => 'Mail Port',
    'mailUsername' => 'Mail Username',
    'mailPassword' => 'Mail Password',
    'mailFrom' => 'Mail From Name',
    'mailFromEmail' => 'Mail From Email',
    'mailEncryption' => 'Mail Encryption',
  ),
  'theme' => 
  array (
    'primaryColor' => 'Primary Color',
    'secondaryColor' => 'Secondary Color',
    'sidebarBgColor' => 'Sidebar Background Color',
    'sidebarTextColor' => 'Sidebar Text Color',
    'topbarTextColor' => 'Topbar Text Color',
    'subheadings' => 
    array (
      'colorPallette' => 'Color Pallette',
      'carouselImages' => 'Carousel Images',
    ),
    'recommendedResolutionNote' => '** Recommended image resolution: 1920 * 1080',
  ),
  'dashboard' => 
  array (
    'totalBooking' => 'Total Bookings',
    'pendingBooking' => 'Pending Bookings',
    'completedBooking' => 'Completed Bookings',
    'canceledBooking' => 'Canceled Bookings',
    'totalCustomers' => 'Total Customers',
    'totalEarning' => 'Total Earnings',
    'recentBookings' => 'Recent Bookings',
    'walkInBookings' => 'Walk-In Bookings',
    'onlineBookings' => 'Online Bookings',
    'inProgressBooking' => 'In Progress Bookings',
  ),
  'update' => 
  array (
    'systemDetails' => 'System Details',
    'updateTitle' => 'Update To New Version',
    'updateDatabase' => 'Update Database',
    'fileReplaceAlert' => 'To update the app to new version check documentation for the instructions.',
    'updateDatabaseButton' => 'Click to update database',
    'newUpdate' => 'New update available',
    'updateNow' => 'Update Now',
    'updateAlternate' => 'If the Update Now button does not work then follow the update instructions as mentioned in the documentation.',
  ),
  'customer' => 
  array (
    'since' => 'Customer Since',
    'search' => 'Search customer by name, email or phone',
    'bookingStats' => 'Booking Stats',
    'contactInfo' => 'Contact Information',
  ),
  'paymentCredential' => 
  array (
    'paypalClientID' => 'Paypal Client ID',
    'stripelClientID' => 'Publishable key',
    'paypalSecret' => 'Paypal Secret',
    'stripeSecret' => 'Secret key',
    'paypalCredential' => 'Paypal Credential',
    'stripeCredential' => 'Stripe Credential',
    'stripeCredentialStatus' => 'Stripe Credential Status',
    'paypalCredentialStatus' => 'Paypal Credential Status',
    'deactive' => 'Deactive',
    'active' => 'Active',
    'stripeWebhookSecret' => 'Stripe Webhook Secret',
    'allowOfflinePayment' => 'Allow Offline Payment',
  ),
  'nexmoCredential' => 
  array (
    'key' => 'Nexmo Key',
    'secret' => 'Nexmo Secret',
    'from' => 'Nexmo From',
    'status' => 'Nexmo Status',
    'active' => 'Active',
    'deactive' => 'Deactive',
  ),
);
